project:
  type: site
  output-dir: _site

execute:
  freeze: auto
  cache: true
  
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    number-sections: true
    html-math-method: katex
    code-copy: true
    code-summary: "Show the code"
    code-overflow: wrap

site:
  title: "MAP566 - Stats in Action"
  repo-url: https://github.com/jchiquet/MAP566
  repo-actions: issue
  page-navigation: true

  navbar:
    logo: logo_X.jpg
    background: primary
    sidebar-menus: true
    left:
      - text: Getting Started
        href: getting-started.qmd
      - icon: github
        href: https://github.com/jchiquet/MAP566
    
    right:
      - sidebar:tests
      - sidebar:regression
      - sidebar:mixed-models
      - sidebar:mixture-models
      - sidebar:multivariate-models
      - sidebar:homework

  sidebar:
    - id: tests
      title: "Hypothesis Testing"
      style: "docked"    
      collapse-level: 2
      align: left
      contents:
        - section: "Lectures"
          contents:
            - docs/tests/map566-lecture-single.Rmd
            - docs/tests/map566-lecture-multiple.Rmd
        - section: "Labs"
          contents:
            - docs/tests/map566-lab-tests.Rmd
        - section: "Documents"
          contents:
            - text: "article"

    - id: regression
      title: "Regression models"
      contents:
        - section: "Lectures"
          contents:
            - docs/regression/map566-lecture-regression-background.Rmd
            - docs/regression/map566-lecture-polynomial-regression.Rmd
            - docs/regression/map566-lecture-nonlinear-regression.Rmd
        - section: "PC/Labs"
          contents:
            - docs/regression/map566-lab-polynomial-regression.Rmd
            - docs/regression/map566-lab-nonlinear-regression.Rmd
    - id: mixed-models
      title: "Mixed models"
      contents:
        - section: "Lectures"
          contents:
            - docs/mixed-models/map566-lecture-linear-mixed-model.Rmd
            - docs/mixed-models/map566-lecture-nonlinear-mixed-model.Rmd
        - section: "PC/Labs"
          contents:
            - docs/mixed-models/map566-lab-linear-mixed-model.Rmd
            - docs/mixed-models/map566-lab-EM-linear-mixed-model.Rmd
            - docs/mixed-models/map566-lab-nonlinear-mixed-model.Rmd

    - id: mixture-models
      title: "Mixture models"
      contents:
        - section: "Lectures"
          contents:
            - docs/mixed-models/map566-lecture-gaussian-mixture-models.Rmd
            - docs/mixed-models/map566-lecture-stochastic-block-models.Rmd
        - section: "PC/Labs"
          contents:
            - docs/mixed-models/map566-lab-gaussian-mixture-models.Rmd
            - docs/mixed-models/map566-lab-stochastic-block-models.Rmd
    - id: multivariate-models
      title: "Multivariate models"
      contents:
        - section: "Lectures"
          contents:
            - docs/mixed-models/map566-lecture-probabilitic-PCA.Rmd
            - docs/mixed-models/map566-lecture-generalized-linear-mixed-models.Rmd
        - section: "PC/Labs"
          contents:
            - docs/mixed-models/map566-lab-probabilitic-PCA.Rmd
            - docs/mixed-models/map566-lab-generalized-linear-mixed-models.Rmd

    - id: homework
      title: "Homework"
        
  footer:
    left: "Last update: November 2021"

bibliography: biblio_MAP566.bib
