project:
  type: site
  output-dir: _site

execute:
  freeze: auto
  cache: true
  
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    number-sections: true
    html-math-method: katex
    code-copy: true
    code-summary: "Show the code"
    code-overflow: wrap

site:
  title: "MAP566 - Stats in Action"
  repo-url: https://github.com/jchiquet/MAP566
  repo-actions: issue
  page-navigation: true

  navbar:
    logo: logo_X.jpg
    background: primary
    sidebar-menus: true
    left:
      - text: Getting Started
        href: getting-started.qmd
      - icon: github
        href: https://github.com/jchiquet/MAP566
    
    right:
      - sidebar:tests
      - sidebar:regression
      - sidebar:mixed-models
      - sidebar:mixture-models
      - sidebar:multivariate-models
      - sidebar:homework

  sidebar:
    - id: tests
      title: "Hypothesis Testing"
      style: "docked"    
      collapse-level: 2
      align: left
      contents:
        - section: "Lectures"
          contents:
            - docs/tests/map566-lecture-single.Rmd
            - docs/tests/map566-lecture-multiple.qmd
        - section: "Labs"
          contents:
            - docs/tests/map566-lab-tests.qmd
        - section: "Documents"
          contents:
            - text: "article"

    - id: regression
      title: "Regression models"
      contents:
        - section: "Lectures"
          contents:
            - docs/regression/map566-lecture-regression-background.qmd
            - docs/regression/map566-lecture-polynomial-regression.qmd
        - section: "PC/Labs"
          contents:
            - docs/regression/map566-lab-polynomial-regression.qmd
            - docs/regression/map566-lab-nonlinear-regression.qmd
    - id: mixed-models
      title: "Mixed models"
      contents:
        - section: "Lectures"
          contents:
            - docs/mixed-models/lectures-lmm.qmd
            - docs/mixed-models/lectures-nlmm.qmd
        - section: "PC/Labs"
          contents:
            - docs/mixed-models/exercices-lmm.qmd
            - docs/mixed-models/exercices-nlmm.qmd

    - id: mixture-models
      title: "Mixture models"
      contents:
        - section: "Lectures"
          contents:
            - docs/mixture-models/lectures-gmm.qmd
            - docs/mixture-models/lectures-sbm.qmd
        - section: "PC/Labs"
          contents:
            - docs/mixture-models/exercices-gmm.qmd
            - docs/mixture-models/exercices-sbm.qmd

    - id: multivariate-models
      title: "Multivariate models"
      contents:
        - section: "Lectures"
          contents:
            - docs/multivar-models/lectures-ppca.qmd
            - docs/multivar-models/lectures-glmm.qmd
        - section: "PC/Labs"
          contents:
            - docs/multivar-models/exercices-ppca.qmd
            - docs/multivar-models/exercices-glmm.qmd

    - id: homework
      title: "Homework"
        
  footer:
    left: "Last update: October 2021"

bibliography: biblio_MAP566.bib
