name: MAP566
channels:
  - conda-forge
  - r
dependencies:
  - r-base>=3.6.2
  - r-tidyverse
#  - r-ggfortify
  - r-knitr
  - r-lattice
  - r-gridextra
  # - r-pwr
  # - r-nlme
  # - r-lme4
  # - r-saemix
  # - r-vgam
