name: MAP566
channels:
  - conda-forge
dependencies:
  - r-base>=4.0.1
  - r-tidyverse
  - r-knitr
  - r-lattice
  - r-gridextra
  - r-nlme
  - r-lme4
  - r-pwr
  - r-saemix
  - r-vgam
  - r-mixtools
  - r-ellipse
  - r-codetools
  - r-corrplot
  - r-ggfortify
  - r-igraph
  - r-aricode
  - r-viridis
  - r-tinytex
  - imagemagick
  
