name: MAP566
channels:
  - conda-forge
  - r
dependencies:
  - r-base>=3.6.2
  - r-tidyverse
  - r-knitr
  - r-lattice
  - r-gridextra
  - r-nlme
  - r-lme4
  - r-pwr
  - r-saemix
  - r-vgam
  - r-mixtools
  # - r-ggfortify
