---
title: "Welcome"
---

## Course description {.unnumbered}

The objective of this course is to show students how statistics is used in practice to answer a specific question, by introducing a series of important model-based approaches.

The students will learn to select and use appropriate statistical methodologies and acquire solid and practical skills by working-out examples on real-world data sets from various areas including medicine, genomics, ecology, and others.

All analyses will be conducted with the R software, possibly with interfacing to Python. No strong knwoledge neither of R nor Python programming is required (only basic scripting).

::: {.callout-note appearance="simple"}

## Important remark {.unnumbered}

Much of the material used in this course is due to [Marc Lavielle](http://www.cmap.polytechnique.fr/~lavielle/), who was the first to set up the [Statistics in Actions](http://sia.webpopix.org/) course.
We only have made some adjustments to it.

:::

## Schedule (tentative) {.unnumbered}

**Teachers** : Julien Chiquet (lecture + 1 PC), Geneviève Robin (2 PC)

**Course Evaluation**: 2 individual homework assignements + a final exam/project 

**Course Language**: French with all material in English

**Numerus closus**: 80 students


1. Statistical tests (x1.5)

    - Two-populations comparison
    - Power analysis
    - Multiple Testing

2. Regression models (x1.5)

    - Linear and Non Linear Regression models
    - Nonlinear regression models
    - Inference Diagnostic, Model comparison

3. Mixed effects models (x2)

    - Linear mixed effects models
    - Nonlinear mixed effects models

4. Mixture models and model-based clustering (x2)

    - Gaussian mixture models for data clustering
    - Stochastic Block Models for graph clustering
    - (Variational) EM algorithm

5. Model-based Dimension Reduction (x2)

    - Multivariate Gaussian model
    - Probabilistic Gaussian PCA
    - Generalized mixed effect models

