name: website
on:
  push:
    branches:
      - main

jobs:
  website:
    name: Build Website with rmarkdown
    if: "contains(github.event.head_commit.message, 'build')"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Setting up miniconda with specified dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: MAP566      

      - name: Installing quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Rendering with Quarto
        shell: bash -l {0}
        run: |
            quarto render 
        
      - name: Deploying website on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true          
